---
title: "G4G on June 20"
output: html_document
---

June 20th, 2021 is this year's summer solstice, the longest day of the year! Also Father's day! What will we do with our 15 hours of sunshine (in Fort Collins Colorado at least)? 

If you want to push yourself to your limits or just enjoy a big day out and support a great non-profit at the same time, consider signing up for our G4G on June 20 event and help Shred the Stigma surrounding mental health.

For the event we will have runners/cyclists/hikers/etc... sign up to move all day on the longest day of the year, setting personal goals for themselves. Each person signed up for the event will recruit sponsors to donate based on achieving their goals. 

For example, my longest run to date was 35 miles in Pisgah National Park over 8ish hours and 5000 feet of gain. I think over a 15-hour day this year I could do 50 miles and 10k vert somewhere in Colorado. I would ask my sponsors to each donate \$50 for the 50 miles and $10 for the vert. 

All fitness levels are welcome! The goal here is to use the day as a goal, a platform, and a way to get out of my/our pandemic blues. Each person who raises over $100 will get a custom 3D viz movie of their all-day workout (see a beta visual below of my Pisgah run). I will also share a 15 hour playlist to keep you motivated out there. 

[Please sign up here](https://forms.gle/59BP4ZzWmwg4wPBe8) if you want to try this out. I will be in touch about how to set your goals, fundraise, and plan for your big day!

You can read more about Go 4 Graham here: [go4graham.org.](https://www.go4graham.org/) 

<iframe src="https://drive.google.com/file/d/1TlMsKbAoeqdF9yCa75oK9BaDvkkWvLMO/preview" width="900" height="550"></iframe>